### ISSUE TITLE
Incorrect link in READ.me

### ISSUE THREAD

**Issue by tanjavos** [STAMP-project/camp#100]
"Checkout the online documentation" points to the Issues. Guess it should point to https://stamp-project.github.io/camp/

;-)

**Comment by fchauvel** [comment]
That’s very correct. Thanks for the feedback! I’ll fix this right away

**Comment by fchauvel** [comment]
Done!

**Comment by monperrus** [comment]
Thanks a lot Tanja, EU experts filling issues on Github, that's the future!
