### ISSUE TITLE
feature for camp for the upcoming release

### ISSUE THREAD

**Issue by vassik** [STAMP-project/camp#15]
Hi @jesus-gorronogoitia, @danzone 

To sum up our recent conversation in context of WP4 about feature for CAMP, I have created an issue where we can discuss features for an upcoming evaluation of CAMP. I have created one issue where I have listed some improvements https://github.com/STAMP-project/camp/issues/14. Please comment here things I forgot to mention or you can just file bugs.

**Comment by fchauvel** [comment]
Closed as no one uses it.
