### ISSUE TITLE
Document the authoring of CAMP required input models

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/camp#18]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: CAMP, latest version
- **Execution Environment**: All platforms
- **Reporter**: Jesús Gorronogoitiazjesus.gorronogoitia@atos.net>

#### Description
Current [CAMP documentation](https://github.com/STAMP-project/camp/blob/master/README.md) does not explicitly describes the required the CAMP input files for configuring the configuration amplification domain model (features.yml, images.yml, genimages.yml, composite.yml, variables.yml) including instructions to generate other domain input models. Examples are given for XWiki and Atos use cases, but not instructions to provide other model instances for other scenarios. Therefore, the application of CAMP in order scenarios requires the support of CAMP technical team.
Therefore, the metamodel of every CAMP input model should be specify in CAMP documentation (or reference to the specifications of these metamodels should be provided) together with examples (code snippets) for relevant modeling elements (e.g. modeling a feature variations, image building rules, etc).

#### Steps to reproduce
N/A
#### Relationships
See #14 for a requirement to specify CAMP input model locations.

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by vassik** [comment]
We describe models partially (an explanation is given on the xwiki example) though I agree that it needs more detailed explanation. We will fix this in the upcoming releases of the tool.

**Comment by fchauvel** [comment]
I tried to describe how to describe the model needed by CAMP. Please check the documentation, and especially, the following pages:
* [CAMP generate](https://stamp-project.github.io/camp/pages/generate.html)
* [CAMP realize](https://stamp-project.github.io/camp/pages/realize.html)
* [The CityGo case study](https://stamp-project.github.io/camp/pages/citygo.html)

I thus close this issue, but feel free to reopen should you not find what you were looking for.
