### ISSUE TITLE
Simplify/Group the different required CAMP input models

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/camp#19]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: CAMP latest version
- **Execution Environment**: All supported platforms
- **Reporter**: Jesús Gorronogoitia <jesus.gorronogoitia@atos.net>

#### Description
Current CAMP tool requires a number of related input models for describing the configuration amplification application domain, including features.yml, images.yml, genimages.yml, composite.yml, variables.yml, etc.
Managing all these models, and providing new instances for different application domains could be complex due to the fragmentation of the CAMP input model across all these models.
We recommend to group all these modeling aspects (features, images, variables, etc) within different subsection of a common CAMP input model (i.e. camp.yml)

#### Steps to reproduce
N/A

#### Relationships
See #18 and #14 

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by vassik** [comment]
This is indeed the case. We should try to consolidate the input. Current input files are features.yml, images.yml, composite.yml, variables.yml (in some use cases).

**Comment by vassik** [comment]
also see #11

**Comment by fchauvel** [comment]
This should be better in v0.2, which consumes only a single input file. See the documentation of the [CityGo case study](https://stamp-project.github.io/camp/pages/citygo.html).

I thus close this issue, but feel free to reopen or open another issue should you have any other problem.
