### ISSUE TITLE
CAMP tool should fail early

### ISSUE THREAD

**Issue by skaark42** [STAMP-project/camp#20]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: sometimes
- **Severity**: major
- **Reporter**: Kenneth Skaar, kenneth.skaar@tellu.no

#### Description
The CAMP tool is actually a series of scripts that are run as one. If one of the first scripts fail for some reason, execution keep going, resulting in misleading and confusing error messages. The start.sh script should check the result of each step of the execution, and bail out as soon as a step fails to complete

#### Steps to reproduce

Run tool with an invalid images.yml file, first step will fail but other steps will still be executed.

**Comment by fchauvel** [comment]
Thanks for the feedback!

As part of the re-packaging process, I am rewriting in Python the part that is currently written in Bash. The new version fails early as Python raises Exception that stop the execution.

**Comment by fchauvel** [comment]
This should be fixed in v0.2.0. I thus close this issue should you face any further problem.
