### ISSUE TITLE
Input files are not validated

### ISSUE THREAD

**Issue by skaark42** [STAMP-project/camp#21]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: sometimes
- **Severity**:  major
- **Reporter**: Kenneth Skaar,kenneth.skaar@tellu.no

#### Description
The contents of the input files are not validated. If some mandatory field is missing, you typically get an error message about an internal datastructure that is invalid. Guessing what is actually wrong is tricky.

Any assumption made by the tool about the input files, should be validated and an appropriate error message should be given if those assumption are broken. 

#### Steps to reproduce
As an example, run the tool with no mandatoryfeature in images.yml

**Comment by fchauvel** [comment]
Thanks a lot for the feedback.

Following a discussion with @vmassol, I'm currently improving the packaging to ease the deployment of CAMP as a standalone application. 

I will focus on validation the input files right after.

**Comment by fchauvel** [comment]
We've integrated a model validation in v0.2.0. I close this issue but feel free to reopen should there be any issue with this feature.
