### ISSUE TITLE
Generated build_images.sh do not work with newer versions of Docker

### ISSUE THREAD

**Issue by brice-morin** [STAMP-project/camp#23]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [camp realize v0.2.1]
- **Execution Environment**: [ubuntu, docker 18.19.0]
- **Reporter**: [@brice-morin]

#### Description

In `camp/samples/stamp/atos/out/config_1/images/build_images.sh`, I had to update the script so that it looks like this (basically remove the `-f` option and instead directly use the folder containing the Dockerfile as argument for the `docker build`):

```bash
docker build -t camp-postgres_0 ./postgres_0
docker build -t camp-showcase_0 ./showcase_0
echo 'All images ready'
```

#### Steps to reproduce

See [ATOS use case](https://stamp-project.github.io/camp/pages/citygo.html)

**Comment by fchauvel** [comment]
Fixed in v0.2.2.
