### ISSUE TITLE
Documentation outdated cannot find docker image

### ISSUE THREAD

**Issue by pedrovelho** [STAMP-project/camp#27]
#### Characteristics

-   **Issue Type**: \[bug]
-   **Reproducibility**: \[always]
-   **Severity**: \[minor]
-   **Tool/Service/Component**: \[camp doc, version]
-   **Execution Environment**: \[linux]
-   **Reporter**: \[Pedro, pedro.velho@activeeon.com]

#### Description

Command on the documentation page is outdated using v1.0.0 [here](https://stamp-project.github.io)./camp/pages/setup.html

#### Steps to reproduce

Just try the command on the documentation [here](https://stamp-project.github.io/camp/pages/setup.html).

```bash
$ docker run -it -v $(pwd):/camp/workspace fchauvel/camp:v1.0.0 camp generate -d workspace
```

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Thanks for the feedback,
 
I close this issue as I updated the installation guide to remove the v1.0.0 which does not exists. The documentation now points towards `fchauvel/camp:latest`.
