### ISSUE TITLE
Fail to install camp from scratch

### ISSUE THREAD

**Issue by danzone** [STAMP-project/camp#32]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: major
-   **Tool/Service/Component**: CAMP, 1.0.0
-   **Execution Environment**: vmi2.stamp-project.eu, Debian Jessie with last updates
-   **Reporter**: Daniele Gagliardi, daniele.gagliardi@eng.it

#### Description
After successfully installing all CAMP prerequisites, I launched CAMP installation with pip, but pip doesn't install anything, showing only the message `Requirement already satisfied: pip from https://github.com/stamp-project/camp.git@master#egg=pip in /usr/local/lib/python2.7/dist-packages (19.0.3)`

#### Steps to reproduce
Execute as root
`root@vmi2:~#` pip install `https://github.com/stamp-project/camp.git@master#egg=pip`
as mentioned in [CAMP documentation](https://stamp-project.github.io/camp/pages/setup.html)

**Comment by fchauvel** [comment]
Thanks for the feedback.

I’ve never tried to install CAMP using PIP directly from a Github
repository. I’ll give it a try and let you know.

I guess the setup.py is wrong.

**Comment by danzone** [comment]
Thank you @fchauvel . In the meanwhile I will give a try to setup.py, just to have some more info

**Comment by fchauvel** [comment]
Here is command that worked for me.

```console
$ pip install -U  git+https://github.com/STAMP-project/camp.git@master#egg=camp
```
I think you saw `requirements already satisfied` because CAMP was somehow already installed. You can specify `-U` (or `--upgrade`) to update it. The command in the documentation is wrong nonetheless: Its ends with `egg=camp` instead of `egg=pip`. Note that you can replace `master` by a commit ID, a tag or a branch to install specific version.

In addition, I also fixed dependencies in the `setup.py` that were missing.

Thanks for the feedback. Feel free to close the issue if the change solve the problem :-)

**Comment by danzone** [comment]
Hi @fchauvel, in the meantime I was able to install it using pip install, cloning the repo in STAMP VM machine. I collected all the logs, in order to track all useful information.

**Comment by danzone** [comment]
Ah, ok, I also tried the setup.py way, and it failed, but, anyway, you fixed it, so we are ok

**Comment by danzone** [comment]
@fchauvel, I'm going to write down all the steps I performed to install CAMP. Anyway, I think we need also an upgrade procedure and an uninstall procedure. I volunteer to write it, because it is also part of WP4 writing documentation for end users.

**Comment by fchauvel** [comment]
I'm working on an alternative [installation script](https://github.com/STAMP-project/camp/blob/master/install.sh) (see Issue #33), to install CAMP directly, instead of using Docker. It installs PIP if it does not already exists, Z3, and CAMP. Maybe this could be a starting point.

While doing this, I just discovered some dependencies. To be install directly as you suggested, CAMP requires `pip` in version 19.0.3, and `setuptools` 40.8.0.

We are still testing this script, but hopefully, we should eventually be able to use as follows:
```bash
$ curl -L https://github.com/STAMP-project/camp/blob/master/install.sh | bash 
```

**Comment by danzone** [comment]
I successfully installed CAMP within STAMP VM (available in STAMP collaborative platform). Following relevant info and steps:
**Platform**: `Debian GNU/Linux 8.11 (jessie)`
**Architecture**: `x86_64`
**Kernel**: `3.16.0-7-amd64`
**Python version**: `Python 2.7.9`
**Z3 Solver**: `Z3 version 4.8.4 - 64 bit - build hashcode d6df51951f4c`
Steps performed (with `root` account):

> \# git clone https://github.com/stamp-project/camp.git

> \# cd camp

> \# pip install -r requirements.txt

This command failed, because it found an existing PyYAML installation:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/STAMP-project/ozepy.git@v1.0.0 (from -r requirements.txt (line 16))
  Cloning https://github.com/STAMP-project/ozepy.git (to revision v1.0.0) to /tmp/pip-req-build-_aX75V
Collecting PyYAML==3.12 (from -r requirements.txt (line 12))
Collecting plumbum==1.6.7 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/48/48/0c592a65c8ecc6a4c0da41d75097704a283595b6731be1531eee3f4f7778/plumbum-1.6.7-py2.py3-none-any.whl
Collecting jsonpath-rw==1.4.0 (from -r requirements.txt (line 14))
Requirement already satisfied: argparse==1.2.1 in /usr/lib/python2.7 (from -r requirements.txt (line 15)) (1.2.1)
Collecting green==2.13.0 (from -r requirements.txt (line 20))
Collecting mock>=2.0.0 (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from jsonpath-rw==1.4.0->-r requirements.txt (line 14)) (1.12.0)
Collecting decorator (from jsonpath-rw==1.4.0->-r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: ply in /usr/lib/python2.7/dist-packages (from jsonpath-rw==1.4.0->-r requirements.txt (line 14)) (3.4)
Collecting colorama (from green==2.13.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting termstyle (from green==2.13.0->-r requirements.txt (line 20))
Collecting unidecode (from green==2.13.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/31/39/53096f9217b057cb049fe872b7fc7ce799a1a89b76cf917d9639e7a558b5/Unidecode-1.0.23-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size>=1.0.0; python_version == "2.7" (from green==2.13.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting coverage (from green==2.13.0->-r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/d7/ce/8553e6325b16d8c2ccba52eaebe92bb38bb7c64c8f34ad4ef87fd327b9bb/coverage-4.5.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->-r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->-r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/14/09/12fe9a14237a6b7e0ba3a8d6fcf254bf4b10ec56a0185f73d651145e9222/pbr-5.1.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from termstyle->green==2.13.0->-r requirements.txt (line 20)) (5.5.1)
Building wheels for collected packages: ozepy
  Building wheel for ozepy (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-KQAWRM/wheels/08/a2/75/5b91ebf89207752b7e8fe5a8ccc0a86fe240f85865b3054746
Successfully built ozepy
Installing collected packages: PyYAML, plumbum, decorator, jsonpath-rw, colorama, funcsigs, pbr, mock, termstyle, unidecode, backports.shutil-get-terminal-size, coverage, green, ozepy
 Found existing installation: PyYAML 3.13
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

In case PyYAML is installed using a package manager (for Debian-based distros, the command is `apt-get install python-yaml`), you should before uninstall it (for Debian-based distros, the command is `apt-get remove python-yaml`).
In case PyYAML is installed from scratch (according to procedure described here: [https://pyyaml.org/wiki/PyYAML](https://pyyaml.org/wiki/PyYAML), re-run the install procedure, redirecting installed files in a text file:
`# python setup.py install --record files.txt`
Then remove PyYAML launching the following command:
`# cat files.txt | xargs rm -rf`

Last command to install camp is simply (within `camp` dir):
`# pip install .`
 Following the output of install procedure:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /root/camp
Building wheels for collected packages: camp
  Building wheel for camp (setup.py) ... done
   Stored in directory: /tmp/pip-ephem-wheel-cache-x9qRKb/wheels/a7/82/c6/4379a5cf788c70bf249106e57e9c3b45e2a6323f74cd7e9372
Successfully built camp
Installing collected packages: camp
Successfully installed camp-0.2.3
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 228, in main
    timeout=min(5, options.timeout)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 93, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 344, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 134, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/misc.py", line 902, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1886, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1405, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1760, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1637, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1594, in load
    mtime = os.stat(path).st_mtime
```
Should camp be already installed, you could see in the installation log a message like this:
```
  Found existing installation: camp 0.2.3
    Uninstalling camp-0.2.3:
      Successfully uninstalled camp-0.2.3
``` 

To check whether camp is correctly installed, launch the following command within an account with no root privileges:
`$ camp -h`
The output should be like the following:
```
usage: CAMP [-h] {generate,realize,execute} ...

Amplify your configuration tests!

positional arguments:
  {generate,realize,execute}
    generate            Generate new test configurations
    realize             Realize the variables in the test configurations
    execute             Execute the test configurations generated

optional arguments:
  -h, --help            show this help message and exit

```
