### ISSUE TITLE
Error when running camp execute on greetings sample

### ISSUE THREAD

**Issue by enriquegit** [STAMP-project/camp#33]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: block
-   **Tool/Service/Component**: camp execute v0.3.0
-   **Execution Environment**: ubuntu
-   **Reporter**: Enrique enrique.garcia-ceja@sintef.no

#### Description
The following error ocurrs when running camp execute
CAMP v0.3.0 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded 'workspace/camp.yaml'.
Loading configurations from 'workspace/out' ...
 - Executing  workspace/out/config_3
   1. Building images ...
      $ bash build_images.sh (from 'workspace/out/config_3/images')
   2. Starting Services ...
      $ docker-compose up -d (from 'workspace/out/config_3')

Test execution aborted!
 - Error: A shell command failed (code: [Errno 2] No such file or directory)
   $ docker-compose up -d
   Check out logs in 'camp_execute.log'.

That's all folks!

#### Steps to reproduce
docker run -it -v $(pwd):/camp/workspace fchauvel/camp:v0.3.0 camp generate -d workspace -a

docker run -it -v $(pwd):/camp/workspace fchauvel/camp:v0.3.0 camp realize -d workspace

docker run -it -v $(pwd):/camp/workspace fchauvel/camp:v0.3.0 camp execute -d workspace -c tests -t maven

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
I just created an alternative way to install CAMP, which I'd like you to try. It's a [shell script](https://github.com/STAMP-project/camp/blob/master/install.sh) that install Z3, and CAMP in one go. Here the command to fetch it and run it. Note that you need to have `git` and `curl`installed locally.

```bash
$ \curl -L https://github.com/STAMP-project/camp/raw/master/install.sh | bash 
```
Just close this issue if you are able to get CAMP installed on your machine with this.

**Comment by fchauvel** [comment]
Hello,

From the log file you emailed me (see below), I think this is a permission problem, which should go away if you run the command as root. Do you have a chance to try it?

Here is the log file, for reference:
```console
camp@bash:./out/config_3/images$ bash build_images.sh
All images ready.

camp@bash:./out/config_3$ docker-compose up -d
Starting config_3_greetings_1 ... 
Starting config_3_tests_1     ... 
[1A[2K
Starting config_3_tests_1     ... [32mdone[0m
[1B[2A[2K
Starting config_3_greetings_1 ... [32mdone[0m
[2B
camp@bash:./out/config_3$ docker-compose run --user=1000 -v /home/enrique/test-execute/camp/samples/java/out/config_3/images/tests_0/:/tests tests mvn test
[ERROR] Could not create local repository at /tests/?/.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
```

**Comment by enriquegit** [comment]
Hi Franck,

I ran the command as root and now it succeeded.

Configuration            RUN   PASS   FAIL  ERROR
--------------------------------------------------
./out/config_3             1      1      0      0
./out/config_2             1      1      0      0
./out/config_1             1      1      0      0
--------------------------------------------------
TOTAL                      3      3      0      0


Best,
Enrique

**Comment by fchauvel** [comment]
Great. I think the problem comes from the Greetings example, which should include a specific "settings.xml" to configure the local repository where maven download the artefacts it needs. I'll give it a try and let you so you can try out.

**Comment by fchauvel** [comment]
I just made some changes so that CAMP accounts for the settings.xml that defines where Maven create its local repository. I think this should let you run the Greetings example without needing to be root.

Could you try the last dev version? To update CAMP, you can simply run
```bash
$ pip install --upgrade git+https://github.com/STAMP-project/camp.git@master#egg=camp
```
We can test the install procedure as well ;-) You also have to checkout the last version of the samples/java example.

**Comment by enriquegit** [comment]
I tried:

pip install --upgrade git+https://github.com/STAMP-project/camp.git@master#egg=camp

camp execute -d . -c tests -t maven
and got the same permission error. However I downloaded and installed CAMP from scratch and the camp execute command was successful without the need for root permissions =). Maybe the pip install –upgrade didn’t get the latest changes?

**Comment by fchauvel** [comment]
Thanks for trying!

The `pip --upgrade` command does not refresh the source code tree, and if you then run `camp execute` against the old example directory `samples/java`, then you'll miss the file `settings.xml` I added in the `template/tests` directory. Does this make sense for you?

I have not understood whether we can close the issue or not? Did the camp execute command eventually worked without the root permission?
