### ISSUE TITLE
No such file or directory when installing CAMP

### ISSUE THREAD

**Issue by enriquegit** [STAMP-project/camp#36]
#### Characteristics

-   **Issue Type**: \[bug]
-   **Reproducibility**: \[always]
-   **Severity**: \[block]
-   **Tool/Service/Component**: \[CAMP 0.3.1]
-   **Execution Environment**: \[ubuntu]
-   **Reporter**: \[Enrique, enrique.garcia-ceja@sintef.no]

#### Description
_**No such file or directory**_ error.

#### Steps to reproduce

The error occurs when following the CAMP [installation guide](https://stamp-project.github.io/camp/pages/setup.html#using-docker). In the second step, when running the command `cd samples/java`

Seems that the 'java' directory does not exist.

#### Other files and URLs
![nodirectory](https://user-images.githubusercontent.com/29730563/55324841-8b897080-5483-11e9-8e17-999f98da2e4c.png)

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Hi,

I can't reproduce this issue. Maybe an old image fchauvel/camp:latest has been cached locally? You can try to update it as follows:
```bash
$ docker pull fchauvel/camp:latest
```
Does it help?

**Comment by enriquegit** [comment]
That solved the error.
