### ISSUE TITLE
Error when running execute

### ISSUE THREAD

**Issue by enriquegit** [STAMP-project/camp#37]
#### Characteristics

-   **Issue Type**: \[bug]
-   **Reproducibility**: \[always]
-   **Severity**: \[block]
-   **Tool/Service/Component**: \[camp, 0.3.1]
-   **Execution Environment**: \[ubuntu]
-   **Reporter**: \[enrique, enrique.garcia-ceja@gmail.com]

#### Description
Error: A shell command failed (code: 1)

#### Steps to reproduce
`docker run --name camp \
             -it \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -t fchauvel/camp:latest bash`

`cd samples/java`

`camp generate -d .`

`camp realize -d .`

`camp execute -d . -c tests -t maven`

And this is the content of camp_execute.log:

camp@bash:./out/config_3/images$ bash build_images.sh
All images ready.

camp@bash:./out/config_3$ docker-compose up -d
config_3_greetings_1 is up-to-date
Starting config_3_tests_1 ... done

camp@bash:./out/config_3$ docker-compose run tests mvn test -B 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.083 s
[INFO] Finished at: 2019-04-01T12:38:51+00:00
[INFO] Final Memory: 8M/275M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/tests). Please verify you invoked Ma
ven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

#### Other files and URLs
![error](https://user-images.githubusercontent.com/29730563/55328467-b62bf700-548c-11e9-8f66-f4b413b7a5dd.png)

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Can't get it to fail on my machine. I wondering what could go wrong on your machine. As we use Docker, the only thing that comes to my mind is that there may remain some irrelevant images built by previous runs of CAMP (e.g., images like "config_X_something ). You can check this with `docker images`.

If there are any, could you remove all of them and retry?

**Comment by brice-morin** [comment]
OK, I am trying now, on a not-too-up-to-date Docker for Windows setup :-) I'll keep you informed.

**Comment by enriquegit** [comment]
Thanks for the pointers. Now it worked after removing all containers and images.

**Comment by brice-morin** [comment]
Works also for me :-)

**Comment by fchauvel** [comment]
I flag this one as a bug and I let it open, as CAMP should specify "--no-cache" when building images.

**Comment by fchauvel** [comment]
I close this becasue CAMP removes all the images it generates since v0.6.4 (see Issue #82).
