### ISSUE TITLE
Add support for execution of performance tests

### ISSUE THREAD

**Issue by danzone** [STAMP-project/camp#42]
#### Characteristics

-   **Issue Type**:feature
-   **Tool/Service/Component**: CAMP 0.3.4, execute module
-   **Execution Environment**: All supported platforms
-   **Reporter**: Daniele Gagliardi, daniele.gagliardi@eng.it

#### Description
During Stockholm meeting, need for supporting performance test emerged (ATOS UC). Apache JMeter has been identified has the target performance test system, so now we need to add the support for JMeter to CAMP execute feature.

**Comment by danzone** [comment]
Dear @fchauvel , if you agree, I will start to setup the code to invoke JMeter within (but of course I will need your support on CAMP internals). I will create a dedicated branch for this.

**Comment by fchauvel** [comment]
Thanks. You may as well fork the repository if you prefer.

**Comment by fchauvel** [comment]
This was done with Release v0.6.0
