### ISSUE TITLE
CAMP documentation

### ISSUE THREAD

**Issue by danzone** [STAMP-project/camp#43]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: minor
-   **Tool/Service/Component**: CAMP Companion website
-   **Execution Environment**: NA
-   **Reporter**: Daniele Gagliardi, daniele.gagliardi@eng.it

#### Description
Companion website has some links to CAMP repositories, mainly for example purposes. For instance, [CAMP execute page](https://stamp-project.github.io/camp/pages/execute.html) has some references to the Java sample webapp, and some files within it. Following the links, it results in "page not found error", because the referenced url is [http://github.com/stamp-project/camp/samples/java](http://github.com/stamp-project/camp/samples/java), while should be [https://github.com/STAMP-project/camp/tree/master/samples/java](https://github.com/STAMP-project/camp/tree/master/samples/java).
#### Steps to reproduce

- go to [CAMP execute page](https://stamp-project.github.io/camp/pages/execute.html) on [CAMP companion web site](https://stamp-project.github.io/)
- follow links to sample assets:
  - [Java Web App](http://github.com/stamp-project/camp/samples/java)
  - [CAMP model](http://github.com/stamp-project/camp/samples/java/camp.yaml)
  - [Deployment template](http://github.com/stamp-project/camp/samples/java/template)
  - [Maven POM file](http://github.com/stamp-project/camp/samples/java/template/greetings/pom.xml)

**Comment by danzone** [comment]
Dear @ffleurey, if you agree, I can fix them

**Comment by fchauvel** [comment]
Thanks. Just open a pull request when you're done.
