### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp#5]
In my opinion, it could be better for CAMP users and developers to have the next points 

**- Camp Samples**
**- Set up your example**  : Brief explanation about files involved 
**- How to run your new configuration**

Best,
Fernando

**Comment by vassik** [comment]
This has been partially done!

**Comment by fchauvel** [comment]
I close this issue as I just revised the documentation. Check out the [new documentation](https://stamp-project.github.io/camp/) and just reopen if you don't find what you'd like.
