### ISSUE TITLE
Problem with some ascii codec...

### ISSUE THREAD

**Issue by brice-morin** [STAMP-project/camp#53]
I am running camp execute on the sphinx use case. I get this error:

```
Unexpected error:
 - 'ascii' codec can't decode byte 0xc3 in position 8123: ordinal not in range(128)
   In file: /usr/lib/python3.5/encodings/ascii.py
      26: return codecs.ascii_decode(input, self.errors)[0]
   Please report this at 'https://github.com/STAMP-project/camp/issues'.

That's all folks!
```

I am using camp from docker-hub: fchauvel/camp. I pulled the latest image, but I am not sure it is up to date. I will try re-building the image locally and see if it helps.

**Comment by fchauvel** [comment]
I do get the same error when running on the new version of the Sphinx experiment. I'll investigate asap, but from the top of my head, it's probably the parsing of the XML report file that fails.
