### ISSUE TITLE
File where substitutions are done is empty in generated configuration

### ISSUE THREAD

**Issue by brice-morin** [STAMP-project/camp#56]
On the atom sample, I am doing substitution in a package.json file

This original file is not empty. However, when calling `camp realize` (after `camp generate`), camp complains that it cannot do substitution:
```
CAMP v0.3.9 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded './camp.yaml'.
Loading configurations from './out' ...

Error:
Vain substitution: No match found!'
  - pattern: '"resolve": "^1.1.6"'
  - target file: './out/config_1/images/atom_0/src/package.json'
Is the pattern approptiate? What about the file content?

That's all folks!
```

The thing is that the file at `./out/config_1/images/atom_0/src/package.json` appears to be empty, hence the vain substitution... Note that all the other files around the package.json file are property copied in the out folder (with content).

**Comment by fchauvel** [comment]
Thanks for the feedback.

I reproduce the problem on my machine. I think it comes from the caret character (^) which has a meaning in Python regular expressions and that would be why Python does not find a match. 

I let you know as soon as I have a fix.

**Comment by fchauvel** [comment]
I pushed a fix, but for some reason the Travis build is broken for a few commits now and I have to fix it before I can release the fix, Otherwise, pull from master and build the docker image locally.

**Comment by brice-morin** [comment]
OK, thanks for the rapid fix. I will rebuild the Docker locally and try

**Comment by fchauvel** [comment]
By the way I fixed sa small typo in the camp.yaml file of the atom
experiment. One of the dependency had twice the same version (I don’t
remember which one but I wrote it in the commit messages)

**Comment by brice-morin** [comment]
OK, thanks! I pulled everything and it seems it works now 👍
