### ISSUE TITLE
"Atomic" mode for CAMP generate

### ISSUE THREAD

**Issue by brice-morin** [STAMP-project/camp#60]
It would be good to have an `--atomic` mode for CAMP generate (or whatever other name for that option).

This mode would still cover all the possible values for all variables, but would only do "atomic changes". In total, if I have one variable A with three values a1, a2, a3, and one variable B with two values b1, b2, it should generate 5 configurations:

- c1 including a1 and doing no substitution for B (assuming the result is consistant if no such substitution is done)
- c2 including a2, and same remark
- c3 including a3, and same remark
- c4 including b1, and doing no substitution for A
-c5 including b2, and same remark

This can be a quite useful intermediate between `--coverage` and `--all`. It is more systematic than `--coverage`, but much less costly than `--all` (basically the number of configuration will be the sum of the number of values, not the product).

I am not sure if z3 supports this, or if we would need to short-circuit z3 in this mode.

It is not a very urgent feature request, as one can simulate this mode by splitting the `camp.yaml` file into "atomic" files and then call `--all` on each of them.

**Comment by brice-morin** [comment]
Or this could be implemented after the camp model is parsed, to transform one camp model with n variables into n camp models with 1 variable, and then run the unmodified machinery on those n models.

**Comment by fchauvel** [comment]
Implemented in 646f1bf33d88c3a5c0cd95af7e8c84e333d6ee68
