### ISSUE TITLE
docker-compose up fails on XWiki sample

### ISSUE THREAD

**Issue by gibello** [STAMP-project/camp#67]
#### Characteristics

-   **Issue Type**: bug
-   **Reproducibility**: always
-   **Severity**: minor
-   **Tool/Service/Component**: CAMP
-   **Execution Environment**: Docker
-   **Reporter**: Pierre-Yves Gibello, pyg@ow2.org

#### Description

Trying to run the sample described here:
https://stamp-project.github.io/camp/pages/xwiki.html

Everything fine until the last instructions in the page:

```
$ cd out/config_1
$ docker-compose -f docker-compose.yml up
ERROR: Invalid interpolation format for "environment" option in service "web": "DB_HOST=&($.services.web.depends_on[0] | $.services.@0.container_name)&"
```

Something wrong in the generated docker-compose.yml file ? Or can't run it inside Docker ??
(note: I used "--coverage", not "--all", for "camp generate").

**Comment by fchauvel** [comment]
Thanks for the feedback.

The XWiki scenario are not executed with CAMP but with an ad hoc technology based TestContainers so, we won't fix this issue.
