### ISSUE TITLE
Recollect docker logs 

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp#99]
#### Characteristics

-   **Issue Type**: feature
-   **Reproducibility**: always
-   **Severity**: feature
-   **Tool/Service/Component**: CAMP version tag:dev
-   **Execution Environment**: Linux
-   **Reporter**: Fernando Mendez - fernando.mendez@atos.net 

#### Description
Include a new feature in CAMP tool to recollect ```docker-compose logs``` or [web service](https://github.com/STAMP-project/camp/blob/master/samples/stamp/atos/functional/template/docker-compose.yml#L79) container logs for each configuration running by CAMP in a execution time for example: ( See 4.1 ) This feature is needed for **STAMP KPI_04**

```
Executing ./out/config_1
1. Building images ...
$ bash build_images.sh --build (from './out/config_1/images')
2. Starting Services ...
$ docker-compose up -d (from './out/config_1')
3. Running tests ...
$ docker-compose run --name camp-tests browser pytest citygo-tests/tests.py --html=nginx-logs/pytest_report.html --junitxml=report.xml --self-contained-html (from './out/config_1')
4. Collecting reports ...
$ docker cp camp-tests:/browser/./ ./test-reports (from './out/config_1')
Reading report.xml

Example: 
4.1 Collecting docker-compose logs or my_web container logs  and send to ./test-reports(from './out/config_1')
$  docker-compose logs >& docker-compose-log.log &
$ docker cp ..... ..... 
````
#### Steps to reproduce
```camp execute -d .```

#### Relationships
Citygo

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Release in CAMP v0.9.0
